\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{blanketmanual}[2024/06/10 Blanket Manual Class]

% Page Width Settings

\LoadClass[11pt]{extarticle}
\RequirePackage[margin = 1in]{geometry}
\RequirePackage{mathtools}

% Spacing Settings

% Table of Contents Settings
\renewcommand{\@pnumwidth}{2.7em}
\renewcommand{\@tocrmarg}{3.7em}

% General Spacing Settings
\setlength{\parindent}{0.75cm}
\setlength{\jot}{0.25ex}

% Page Header Settings
\setlength{\headheight}{15pt}
\addtolength{\topmargin}{-3.0pt}